export const ISO_4217_SNAPSHOT_PUBLISHED = '2026-01-01' as const;
export const ISO_4217_SNAPSHOT_SHA256 = '838dfb991648cf36df939edd5fe3811737962b75a32252847d239cedd1e291c9' as const;

export interface Iso4217Currency {
  readonly numericCode: number;
  readonly alphaCode: string;
  readonly name: string;
  readonly minorUnits: number | null;
  readonly territories: readonly string[];
}

export const ISO_4217_CURRENCIES: readonly Iso4217Currency[] = [
  { numericCode: 8, alphaCode: 'ALL', name: 'Lek', minorUnits: 2, territories: ['ALBANIA'] },
  { numericCode: 12, alphaCode: 'DZD', name: 'Algerian Dinar', minorUnits: 2, territories: ['ALGERIA'] },
  { numericCode: 32, alphaCode: 'ARS', name: 'Argentine Peso', minorUnits: 2, territories: ['ARGENTINA'] },
  {
    numericCode: 36,
    alphaCode: 'AUD',
    name: 'Australian Dollar',
    minorUnits: 2,
    territories: [
      'AUSTRALIA',
      'CHRISTMAS ISLAND',
      'COCOS (KEELING) ISLANDS (THE)',
      'HEARD ISLAND AND McDONALD ISLANDS',
      'KIRIBATI',
      'NAURU',
      'NORFOLK ISLAND',
      'TUVALU',
    ],
  },
  { numericCode: 44, alphaCode: 'BSD', name: 'Bahamian Dollar', minorUnits: 2, territories: ['BAHAMAS (THE)'] },
  { numericCode: 48, alphaCode: 'BHD', name: 'Bahraini Dinar', minorUnits: 3, territories: ['BAHRAIN'] },
  { numericCode: 50, alphaCode: 'BDT', name: 'Taka', minorUnits: 2, territories: ['BANGLADESH'] },
  { numericCode: 51, alphaCode: 'AMD', name: 'Armenian Dram', minorUnits: 2, territories: ['ARMENIA'] },
  { numericCode: 52, alphaCode: 'BBD', name: 'Barbados Dollar', minorUnits: 2, territories: ['BARBADOS'] },
  { numericCode: 60, alphaCode: 'BMD', name: 'Bermudian Dollar', minorUnits: 2, territories: ['BERMUDA'] },
  { numericCode: 64, alphaCode: 'BTN', name: 'Ngultrum', minorUnits: 2, territories: ['BHUTAN'] },
  {
    numericCode: 68,
    alphaCode: 'BOB',
    name: 'Boliviano',
    minorUnits: 2,
    territories: ['BOLIVIA (PLURINATIONAL STATE OF)'],
  },
  { numericCode: 72, alphaCode: 'BWP', name: 'Pula', minorUnits: 2, territories: ['BOTSWANA'] },
  { numericCode: 84, alphaCode: 'BZD', name: 'Belize Dollar', minorUnits: 2, territories: ['BELIZE'] },
  {
    numericCode: 90,
    alphaCode: 'SBD',
    name: 'Solomon Islands Dollar',
    minorUnits: 2,
    territories: ['SOLOMON ISLANDS'],
  },
  { numericCode: 96, alphaCode: 'BND', name: 'Brunei Dollar', minorUnits: 2, territories: ['BRUNEI DARUSSALAM'] },
  { numericCode: 104, alphaCode: 'MMK', name: 'Kyat', minorUnits: 2, territories: ['MYANMAR'] },
  { numericCode: 108, alphaCode: 'BIF', name: 'Burundi Franc', minorUnits: 0, territories: ['BURUNDI'] },
  { numericCode: 116, alphaCode: 'KHR', name: 'Riel', minorUnits: 2, territories: ['CAMBODIA'] },
  { numericCode: 124, alphaCode: 'CAD', name: 'Canadian Dollar', minorUnits: 2, territories: ['CANADA'] },
  { numericCode: 132, alphaCode: 'CVE', name: 'Cabo Verde Escudo', minorUnits: 2, territories: ['CABO VERDE'] },
  {
    numericCode: 136,
    alphaCode: 'KYD',
    name: 'Cayman Islands Dollar',
    minorUnits: 2,
    territories: ['CAYMAN ISLANDS (THE)'],
  },
  { numericCode: 144, alphaCode: 'LKR', name: 'Sri Lanka Rupee', minorUnits: 2, territories: ['SRI LANKA'] },
  { numericCode: 152, alphaCode: 'CLP', name: 'Chilean Peso', minorUnits: 0, territories: ['CHILE'] },
  { numericCode: 156, alphaCode: 'CNY', name: 'Yuan Renminbi', minorUnits: 2, territories: ['CHINA'] },
  { numericCode: 170, alphaCode: 'COP', name: 'Colombian Peso', minorUnits: 2, territories: ['COLOMBIA'] },
  { numericCode: 174, alphaCode: 'KMF', name: 'Comorian Franc ', minorUnits: 0, territories: ['COMOROS (THE)'] },
  { numericCode: 188, alphaCode: 'CRC', name: 'Costa Rican Colon', minorUnits: 2, territories: ['COSTA RICA'] },
  { numericCode: 192, alphaCode: 'CUP', name: 'Cuban Peso', minorUnits: 2, territories: ['CUBA'] },
  { numericCode: 203, alphaCode: 'CZK', name: 'Czech Koruna', minorUnits: 2, territories: ['CZECHIA'] },
  {
    numericCode: 208,
    alphaCode: 'DKK',
    name: 'Danish Krone',
    minorUnits: 2,
    territories: ['DENMARK', 'FAROE ISLANDS (THE)', 'GREENLAND'],
  },
  {
    numericCode: 214,
    alphaCode: 'DOP',
    name: 'Dominican Peso',
    minorUnits: 2,
    territories: ['DOMINICAN REPUBLIC (THE)'],
  },
  { numericCode: 222, alphaCode: 'SVC', name: 'El Salvador Colon', minorUnits: 2, territories: ['EL SALVADOR'] },
  { numericCode: 230, alphaCode: 'ETB', name: 'Ethiopian Birr', minorUnits: 2, territories: ['ETHIOPIA'] },
  { numericCode: 232, alphaCode: 'ERN', name: 'Nakfa', minorUnits: 2, territories: ['ERITREA'] },
  {
    numericCode: 238,
    alphaCode: 'FKP',
    name: 'Falkland Islands Pound',
    minorUnits: 2,
    territories: ['FALKLAND ISLANDS (THE) [MALVINAS]'],
  },
  { numericCode: 242, alphaCode: 'FJD', name: 'Fiji Dollar', minorUnits: 2, territories: ['FIJI'] },
  { numericCode: 262, alphaCode: 'DJF', name: 'Djibouti Franc', minorUnits: 0, territories: ['DJIBOUTI'] },
  { numericCode: 270, alphaCode: 'GMD', name: 'Dalasi', minorUnits: 2, territories: ['GAMBIA (THE)'] },
  { numericCode: 292, alphaCode: 'GIP', name: 'Gibraltar Pound', minorUnits: 2, territories: ['GIBRALTAR'] },
  { numericCode: 320, alphaCode: 'GTQ', name: 'Quetzal', minorUnits: 2, territories: ['GUATEMALA'] },
  { numericCode: 324, alphaCode: 'GNF', name: 'Guinean Franc', minorUnits: 0, territories: ['GUINEA'] },
  { numericCode: 328, alphaCode: 'GYD', name: 'Guyana Dollar', minorUnits: 2, territories: ['GUYANA'] },
  { numericCode: 332, alphaCode: 'HTG', name: 'Gourde', minorUnits: 2, territories: ['HAITI'] },
  { numericCode: 340, alphaCode: 'HNL', name: 'Lempira', minorUnits: 2, territories: ['HONDURAS'] },
  { numericCode: 344, alphaCode: 'HKD', name: 'Hong Kong Dollar', minorUnits: 2, territories: ['HONG KONG'] },
  { numericCode: 348, alphaCode: 'HUF', name: 'Forint', minorUnits: 2, territories: ['HUNGARY'] },
  { numericCode: 352, alphaCode: 'ISK', name: 'Iceland Krona', minorUnits: 0, territories: ['ICELAND'] },
  { numericCode: 356, alphaCode: 'INR', name: 'Indian Rupee', minorUnits: 2, territories: ['BHUTAN', 'INDIA'] },
  { numericCode: 360, alphaCode: 'IDR', name: 'Rupiah', minorUnits: 2, territories: ['INDONESIA'] },
  {
    numericCode: 364,
    alphaCode: 'IRR',
    name: 'Iranian Rial',
    minorUnits: 2,
    territories: ['IRAN (ISLAMIC REPUBLIC OF)'],
  },
  { numericCode: 368, alphaCode: 'IQD', name: 'Iraqi Dinar', minorUnits: 3, territories: ['IRAQ'] },
  { numericCode: 376, alphaCode: 'ILS', name: 'New Israeli Sheqel', minorUnits: 2, territories: ['ISRAEL'] },
  { numericCode: 388, alphaCode: 'JMD', name: 'Jamaican Dollar', minorUnits: 2, territories: ['JAMAICA'] },
  { numericCode: 392, alphaCode: 'JPY', name: 'Yen', minorUnits: 0, territories: ['JAPAN'] },
  {
    numericCode: 396,
    alphaCode: 'XAD',
    name: 'Arab Accounting Dinar',
    minorUnits: 2,
    territories: ['ARAB MONETARY FUND'],
  },
  { numericCode: 398, alphaCode: 'KZT', name: 'Tenge', minorUnits: 2, territories: ['KAZAKHSTAN'] },
  { numericCode: 400, alphaCode: 'JOD', name: 'Jordanian Dinar', minorUnits: 3, territories: ['JORDAN'] },
  { numericCode: 404, alphaCode: 'KES', name: 'Kenyan Shilling', minorUnits: 2, territories: ['KENYA'] },
  {
    numericCode: 408,
    alphaCode: 'KPW',
    name: 'North Korean Won',
    minorUnits: 2,
    territories: ['KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)'],
  },
  { numericCode: 410, alphaCode: 'KRW', name: 'Won', minorUnits: 0, territories: ['KOREA (THE REPUBLIC OF)'] },
  { numericCode: 414, alphaCode: 'KWD', name: 'Kuwaiti Dinar', minorUnits: 3, territories: ['KUWAIT'] },
  { numericCode: 417, alphaCode: 'KGS', name: 'Som', minorUnits: 2, territories: ['KYRGYZSTAN'] },
  {
    numericCode: 418,
    alphaCode: 'LAK',
    name: 'Lao Kip',
    minorUnits: 2,
    territories: ['LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)'],
  },
  { numericCode: 422, alphaCode: 'LBP', name: 'Lebanese Pound', minorUnits: 2, territories: ['LEBANON'] },
  { numericCode: 426, alphaCode: 'LSL', name: 'Loti', minorUnits: 2, territories: ['LESOTHO'] },
  { numericCode: 430, alphaCode: 'LRD', name: 'Liberian Dollar', minorUnits: 2, territories: ['LIBERIA'] },
  { numericCode: 434, alphaCode: 'LYD', name: 'Libyan Dinar', minorUnits: 3, territories: ['LIBYA'] },
  { numericCode: 446, alphaCode: 'MOP', name: 'Pataca', minorUnits: 2, territories: ['MACAO'] },
  { numericCode: 454, alphaCode: 'MWK', name: 'Malawi Kwacha', minorUnits: 2, territories: ['MALAWI'] },
  { numericCode: 458, alphaCode: 'MYR', name: 'Malaysian Ringgit', minorUnits: 2, territories: ['MALAYSIA'] },
  { numericCode: 462, alphaCode: 'MVR', name: 'Rufiyaa', minorUnits: 2, territories: ['MALDIVES'] },
  { numericCode: 480, alphaCode: 'MUR', name: 'Mauritius Rupee', minorUnits: 2, territories: ['MAURITIUS'] },
  { numericCode: 484, alphaCode: 'MXN', name: 'Mexican Peso', minorUnits: 2, territories: ['MEXICO'] },
  { numericCode: 496, alphaCode: 'MNT', name: 'Tugrik', minorUnits: 2, territories: ['MONGOLIA'] },
  {
    numericCode: 498,
    alphaCode: 'MDL',
    name: 'Moldovan Leu',
    minorUnits: 2,
    territories: ['MOLDOVA (THE REPUBLIC OF)'],
  },
  {
    numericCode: 504,
    alphaCode: 'MAD',
    name: 'Moroccan Dirham',
    minorUnits: 2,
    territories: ['MOROCCO', 'WESTERN SAHARA'],
  },
  { numericCode: 512, alphaCode: 'OMR', name: 'Rial Omani', minorUnits: 3, territories: ['OMAN'] },
  { numericCode: 516, alphaCode: 'NAD', name: 'Namibia Dollar', minorUnits: 2, territories: ['NAMIBIA'] },
  { numericCode: 524, alphaCode: 'NPR', name: 'Nepalese Rupee', minorUnits: 2, territories: ['NEPAL'] },
  {
    numericCode: 532,
    alphaCode: 'XCG',
    name: 'Caribbean Guilder',
    minorUnits: 2,
    territories: ['CURAÇAO', 'SINT MAARTEN (DUTCH PART)'],
  },
  { numericCode: 533, alphaCode: 'AWG', name: 'Aruban Florin', minorUnits: 2, territories: ['ARUBA'] },
  { numericCode: 548, alphaCode: 'VUV', name: 'Vatu', minorUnits: 0, territories: ['VANUATU'] },
  {
    numericCode: 554,
    alphaCode: 'NZD',
    name: 'New Zealand Dollar',
    minorUnits: 2,
    territories: ['COOK ISLANDS (THE)', 'NEW ZEALAND', 'NIUE', 'PITCAIRN', 'TOKELAU'],
  },
  { numericCode: 558, alphaCode: 'NIO', name: 'Cordoba Oro', minorUnits: 2, territories: ['NICARAGUA'] },
  { numericCode: 566, alphaCode: 'NGN', name: 'Naira', minorUnits: 2, territories: ['NIGERIA'] },
  {
    numericCode: 578,
    alphaCode: 'NOK',
    name: 'Norwegian Krone',
    minorUnits: 2,
    territories: ['BOUVET ISLAND', 'NORWAY', 'SVALBARD AND JAN MAYEN'],
  },
  { numericCode: 586, alphaCode: 'PKR', name: 'Pakistan Rupee', minorUnits: 2, territories: ['PAKISTAN'] },
  { numericCode: 590, alphaCode: 'PAB', name: 'Balboa', minorUnits: 2, territories: ['PANAMA'] },
  { numericCode: 598, alphaCode: 'PGK', name: 'Kina', minorUnits: 2, territories: ['PAPUA NEW GUINEA'] },
  { numericCode: 600, alphaCode: 'PYG', name: 'Guarani', minorUnits: 0, territories: ['PARAGUAY'] },
  { numericCode: 604, alphaCode: 'PEN', name: 'Sol', minorUnits: 2, territories: ['PERU'] },
  { numericCode: 608, alphaCode: 'PHP', name: 'Philippine Peso', minorUnits: 2, territories: ['PHILIPPINES (THE)'] },
  { numericCode: 634, alphaCode: 'QAR', name: 'Qatari Rial', minorUnits: 2, territories: ['QATAR'] },
  {
    numericCode: 643,
    alphaCode: 'RUB',
    name: 'Russian Ruble',
    minorUnits: 2,
    territories: ['RUSSIAN FEDERATION (THE)'],
  },
  { numericCode: 646, alphaCode: 'RWF', name: 'Rwanda Franc', minorUnits: 0, territories: ['RWANDA'] },
  {
    numericCode: 654,
    alphaCode: 'SHP',
    name: 'Saint Helena Pound',
    minorUnits: 2,
    territories: ['SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA'],
  },
  { numericCode: 682, alphaCode: 'SAR', name: 'Saudi Riyal', minorUnits: 2, territories: ['SAUDI ARABIA'] },
  { numericCode: 690, alphaCode: 'SCR', name: 'Seychelles Rupee', minorUnits: 2, territories: ['SEYCHELLES'] },
  { numericCode: 702, alphaCode: 'SGD', name: 'Singapore Dollar', minorUnits: 2, territories: ['SINGAPORE'] },
  { numericCode: 704, alphaCode: 'VND', name: 'Dong', minorUnits: 0, territories: ['VIET NAM'] },
  { numericCode: 706, alphaCode: 'SOS', name: 'Somali Shilling', minorUnits: 2, territories: ['SOMALIA'] },
  {
    numericCode: 710,
    alphaCode: 'ZAR',
    name: 'Rand',
    minorUnits: 2,
    territories: ['LESOTHO', 'NAMIBIA', 'SOUTH AFRICA'],
  },
  { numericCode: 728, alphaCode: 'SSP', name: 'South Sudanese Pound', minorUnits: 2, territories: ['SOUTH SUDAN'] },
  { numericCode: 748, alphaCode: 'SZL', name: 'Lilangeni', minorUnits: 2, territories: ['ESWATINI'] },
  { numericCode: 752, alphaCode: 'SEK', name: 'Swedish Krona', minorUnits: 2, territories: ['SWEDEN'] },
  {
    numericCode: 756,
    alphaCode: 'CHF',
    name: 'Swiss Franc',
    minorUnits: 2,
    territories: ['LIECHTENSTEIN', 'SWITZERLAND'],
  },
  { numericCode: 760, alphaCode: 'SYP', name: 'Syrian Pound', minorUnits: 2, territories: ['SYRIAN ARAB REPUBLIC'] },
  { numericCode: 764, alphaCode: 'THB', name: 'Baht', minorUnits: 2, territories: ['THAILAND'] },
  { numericCode: 776, alphaCode: 'TOP', name: 'Pa’anga', minorUnits: 2, territories: ['TONGA'] },
  {
    numericCode: 780,
    alphaCode: 'TTD',
    name: 'Trinidad and Tobago Dollar',
    minorUnits: 2,
    territories: ['TRINIDAD AND TOBAGO'],
  },
  {
    numericCode: 784,
    alphaCode: 'AED',
    name: 'UAE Dirham',
    minorUnits: 2,
    territories: ['UNITED ARAB EMIRATES (THE)'],
  },
  { numericCode: 788, alphaCode: 'TND', name: 'Tunisian Dinar', minorUnits: 3, territories: ['TUNISIA'] },
  { numericCode: 800, alphaCode: 'UGX', name: 'Uganda Shilling', minorUnits: 0, territories: ['UGANDA'] },
  { numericCode: 807, alphaCode: 'MKD', name: 'Denar', minorUnits: 2, territories: ['NORTH MACEDONIA'] },
  { numericCode: 818, alphaCode: 'EGP', name: 'Egyptian Pound', minorUnits: 2, territories: ['EGYPT'] },
  {
    numericCode: 826,
    alphaCode: 'GBP',
    name: 'Pound Sterling',
    minorUnits: 2,
    territories: ['GUERNSEY', 'ISLE OF MAN', 'JERSEY', 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)'],
  },
  {
    numericCode: 834,
    alphaCode: 'TZS',
    name: 'Tanzanian Shilling',
    minorUnits: 2,
    territories: ['TANZANIA, UNITED REPUBLIC OF'],
  },
  {
    numericCode: 840,
    alphaCode: 'USD',
    name: 'US Dollar',
    minorUnits: 2,
    territories: [
      'AMERICAN SAMOA',
      'BONAIRE, SINT EUSTATIUS AND SABA',
      'BRITISH INDIAN OCEAN TERRITORY (THE)',
      'ECUADOR',
      'EL SALVADOR',
      'GUAM',
      'HAITI',
      'MARSHALL ISLANDS (THE)',
      'MICRONESIA (FEDERATED STATES OF)',
      'NORTHERN MARIANA ISLANDS (THE)',
      'PALAU',
      'PANAMA',
      'PUERTO RICO',
      'TIMOR-LESTE',
      'TURKS AND CAICOS ISLANDS (THE)',
      'UNITED STATES MINOR OUTLYING ISLANDS (THE)',
      'UNITED STATES OF AMERICA (THE)',
      'VIRGIN ISLANDS (BRITISH)',
      'VIRGIN ISLANDS (U.S.)',
    ],
  },
  { numericCode: 858, alphaCode: 'UYU', name: 'Peso Uruguayo', minorUnits: 2, territories: ['URUGUAY'] },
  { numericCode: 860, alphaCode: 'UZS', name: 'Uzbekistan Sum', minorUnits: 2, territories: ['UZBEKISTAN'] },
  { numericCode: 882, alphaCode: 'WST', name: 'Tala', minorUnits: 2, territories: ['SAMOA'] },
  { numericCode: 886, alphaCode: 'YER', name: 'Yemeni Rial', minorUnits: 2, territories: ['YEMEN'] },
  {
    numericCode: 901,
    alphaCode: 'TWD',
    name: 'New Taiwan Dollar',
    minorUnits: 2,
    territories: ['TAIWAN (PROVINCE OF CHINA)'],
  },
  { numericCode: 924, alphaCode: 'ZWG', name: 'Zimbabwe Gold', minorUnits: 2, territories: ['ZIMBABWE'] },
  { numericCode: 925, alphaCode: 'SLE', name: 'Leone', minorUnits: 2, territories: ['SIERRA LEONE'] },
  {
    numericCode: 926,
    alphaCode: 'VED',
    name: 'Bolívar Soberano',
    minorUnits: 2,
    territories: ['VENEZUELA (BOLIVARIAN REPUBLIC OF)'],
  },
  { numericCode: 927, alphaCode: 'UYW', name: 'Unidad Previsional', minorUnits: 4, territories: ['URUGUAY'] },
  {
    numericCode: 928,
    alphaCode: 'VES',
    name: 'Bolívar Soberano',
    minorUnits: 2,
    territories: ['VENEZUELA (BOLIVARIAN REPUBLIC OF)'],
  },
  { numericCode: 929, alphaCode: 'MRU', name: 'Ouguiya', minorUnits: 2, territories: ['MAURITANIA'] },
  { numericCode: 930, alphaCode: 'STN', name: 'Dobra', minorUnits: 2, territories: ['SAO TOME AND PRINCIPE'] },
  { numericCode: 933, alphaCode: 'BYN', name: 'Belarusian Ruble', minorUnits: 2, territories: ['BELARUS'] },
  { numericCode: 934, alphaCode: 'TMT', name: 'Turkmenistan New Manat', minorUnits: 2, territories: ['TURKMENISTAN'] },
  { numericCode: 936, alphaCode: 'GHS', name: 'Ghana Cedi', minorUnits: 2, territories: ['GHANA'] },
  { numericCode: 938, alphaCode: 'SDG', name: 'Sudanese Pound', minorUnits: 2, territories: ['SUDAN (THE)'] },
  {
    numericCode: 940,
    alphaCode: 'UYI',
    name: 'Uruguay Peso en Unidades Indexadas (UI)',
    minorUnits: 0,
    territories: ['URUGUAY'],
  },
  { numericCode: 941, alphaCode: 'RSD', name: 'Serbian Dinar', minorUnits: 2, territories: ['SERBIA'] },
  { numericCode: 943, alphaCode: 'MZN', name: 'Mozambique Metical', minorUnits: 2, territories: ['MOZAMBIQUE'] },
  { numericCode: 944, alphaCode: 'AZN', name: 'Azerbaijan Manat', minorUnits: 2, territories: ['AZERBAIJAN'] },
  { numericCode: 946, alphaCode: 'RON', name: 'Romanian Leu', minorUnits: 2, territories: ['ROMANIA'] },
  { numericCode: 947, alphaCode: 'CHE', name: 'WIR Euro', minorUnits: 2, territories: ['SWITZERLAND'] },
  { numericCode: 948, alphaCode: 'CHW', name: 'WIR Franc', minorUnits: 2, territories: ['SWITZERLAND'] },
  { numericCode: 949, alphaCode: 'TRY', name: 'Turkish Lira', minorUnits: 2, territories: ['TÜRKİYE'] },
  {
    numericCode: 950,
    alphaCode: 'XAF',
    name: 'CFA Franc BEAC',
    minorUnits: 0,
    territories: ['CAMEROON', 'CENTRAL AFRICAN REPUBLIC (THE)', 'CHAD', 'CONGO (THE)', 'EQUATORIAL GUINEA', 'GABON'],
  },
  {
    numericCode: 951,
    alphaCode: 'XCD',
    name: 'East Caribbean Dollar',
    minorUnits: 2,
    territories: [
      'ANGUILLA',
      'ANTIGUA AND BARBUDA',
      'DOMINICA',
      'GRENADA',
      'MONTSERRAT',
      'SAINT KITTS AND NEVIS',
      'SAINT LUCIA',
      'SAINT VINCENT AND THE GRENADINES',
    ],
  },
  {
    numericCode: 952,
    alphaCode: 'XOF',
    name: 'CFA Franc BCEAO',
    minorUnits: 0,
    territories: ['BENIN', 'BURKINA FASO', "CÔTE D'IVOIRE", 'GUINEA-BISSAU', 'MALI', 'NIGER (THE)', 'SENEGAL', 'TOGO'],
  },
  {
    numericCode: 953,
    alphaCode: 'XPF',
    name: 'CFP Franc',
    minorUnits: 0,
    territories: ['FRENCH POLYNESIA', 'NEW CALEDONIA', 'WALLIS AND FUTUNA'],
  },
  {
    numericCode: 955,
    alphaCode: 'XBA',
    name: 'Bond Markets Unit European Composite Unit (EURCO)',
    minorUnits: null,
    territories: ['ZZ01_Bond Markets Unit European_EURCO'],
  },
  {
    numericCode: 956,
    alphaCode: 'XBB',
    name: 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
    minorUnits: null,
    territories: ['ZZ02_Bond Markets Unit European_EMU-6'],
  },
  {
    numericCode: 957,
    alphaCode: 'XBC',
    name: 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
    minorUnits: null,
    territories: ['ZZ03_Bond Markets Unit European_EUA-9'],
  },
  {
    numericCode: 958,
    alphaCode: 'XBD',
    name: 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
    minorUnits: null,
    territories: ['ZZ04_Bond Markets Unit European_EUA-17'],
  },
  { numericCode: 959, alphaCode: 'XAU', name: 'Gold', minorUnits: null, territories: ['ZZ08_Gold'] },
  {
    numericCode: 960,
    alphaCode: 'XDR',
    name: 'SDR (Special Drawing Right)',
    minorUnits: null,
    territories: ['INTERNATIONAL MONETARY FUND (IMF) '],
  },
  { numericCode: 961, alphaCode: 'XAG', name: 'Silver', minorUnits: null, territories: ['ZZ11_Silver'] },
  { numericCode: 962, alphaCode: 'XPT', name: 'Platinum', minorUnits: null, territories: ['ZZ10_Platinum'] },
  {
    numericCode: 963,
    alphaCode: 'XTS',
    name: 'Codes specifically reserved for testing purposes',
    minorUnits: null,
    territories: ['ZZ06_Testing_Code'],
  },
  { numericCode: 964, alphaCode: 'XPD', name: 'Palladium', minorUnits: null, territories: ['ZZ09_Palladium'] },
  {
    numericCode: 965,
    alphaCode: 'XUA',
    name: 'ADB Unit of Account',
    minorUnits: null,
    territories: ['MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP'],
  },
  { numericCode: 967, alphaCode: 'ZMW', name: 'Zambian Kwacha', minorUnits: 2, territories: ['ZAMBIA'] },
  { numericCode: 968, alphaCode: 'SRD', name: 'Surinam Dollar', minorUnits: 2, territories: ['SURINAME'] },
  { numericCode: 969, alphaCode: 'MGA', name: 'Malagasy Ariary', minorUnits: 2, territories: ['MADAGASCAR'] },
  { numericCode: 970, alphaCode: 'COU', name: 'Unidad de Valor Real', minorUnits: 2, territories: ['COLOMBIA'] },
  { numericCode: 971, alphaCode: 'AFN', name: 'Afghani', minorUnits: 2, territories: ['AFGHANISTAN'] },
  { numericCode: 972, alphaCode: 'TJS', name: 'Somoni', minorUnits: 2, territories: ['TAJIKISTAN'] },
  { numericCode: 973, alphaCode: 'AOA', name: 'Kwanza', minorUnits: 2, territories: ['ANGOLA'] },
  {
    numericCode: 976,
    alphaCode: 'CDF',
    name: 'Congolese Franc',
    minorUnits: 2,
    territories: ['CONGO (THE DEMOCRATIC REPUBLIC OF THE)'],
  },
  {
    numericCode: 977,
    alphaCode: 'BAM',
    name: 'Convertible Mark',
    minorUnits: 2,
    territories: ['BOSNIA AND HERZEGOVINA'],
  },
  {
    numericCode: 978,
    alphaCode: 'EUR',
    name: 'Euro',
    minorUnits: 2,
    territories: [
      'ANDORRA',
      'AUSTRIA',
      'BELGIUM',
      'BULGARIA',
      'CROATIA',
      'CYPRUS',
      'ESTONIA',
      'EUROPEAN UNION',
      'FINLAND',
      'FRANCE',
      'FRENCH GUIANA',
      'FRENCH SOUTHERN TERRITORIES (THE)',
      'GERMANY',
      'GREECE',
      'GUADELOUPE',
      'HOLY SEE (THE)',
      'IRELAND',
      'ITALY',
      'LATVIA',
      'LITHUANIA',
      'LUXEMBOURG',
      'MALTA',
      'MARTINIQUE',
      'MAYOTTE',
      'MONACO',
      'MONTENEGRO',
      'NETHERLANDS (THE)',
      'PORTUGAL',
      'RÉUNION',
      'SAINT BARTHÉLEMY',
      'SAINT MARTIN (FRENCH PART)',
      'SAINT PIERRE AND MIQUELON',
      'SAN MARINO',
      'SLOVAKIA',
      'SLOVENIA',
      'SPAIN',
      'ÅLAND ISLANDS',
    ],
  },
  {
    numericCode: 979,
    alphaCode: 'MXV',
    name: 'Mexican Unidad de Inversion (UDI)',
    minorUnits: 2,
    territories: ['MEXICO'],
  },
  { numericCode: 980, alphaCode: 'UAH', name: 'Hryvnia', minorUnits: 2, territories: ['UKRAINE'] },
  { numericCode: 981, alphaCode: 'GEL', name: 'Lari', minorUnits: 2, territories: ['GEORGIA'] },
  {
    numericCode: 984,
    alphaCode: 'BOV',
    name: 'Mvdol',
    minorUnits: 2,
    territories: ['BOLIVIA (PLURINATIONAL STATE OF)'],
  },
  { numericCode: 985, alphaCode: 'PLN', name: 'Zloty', minorUnits: 2, territories: ['POLAND'] },
  { numericCode: 986, alphaCode: 'BRL', name: 'Brazilian Real', minorUnits: 2, territories: ['BRAZIL'] },
  { numericCode: 990, alphaCode: 'CLF', name: 'Unidad de Fomento', minorUnits: 4, territories: ['CHILE'] },
  {
    numericCode: 994,
    alphaCode: 'XSU',
    name: 'Sucre',
    minorUnits: null,
    territories: ['SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"'],
  },
  {
    numericCode: 997,
    alphaCode: 'USN',
    name: 'US Dollar (Next day)',
    minorUnits: 2,
    territories: ['UNITED STATES OF AMERICA (THE)'],
  },
  {
    numericCode: 999,
    alphaCode: 'XXX',
    name: 'The codes assigned for transactions where no currency is involved',
    minorUnits: null,
    territories: ['ZZ07_No_Currency'],
  },
];

const byNumericCode = new Map(ISO_4217_CURRENCIES.map((currency) => [currency.numericCode, currency]));
const englishCurrencyNames = new Intl.DisplayNames(['en'], { type: 'currency' });

const NON_ISSUANCE_ALPHA_CODES = new Set([
  'BOV',
  'CHE',
  'CHW',
  'CLF',
  'COU',
  'MXV',
  'USN',
  'UYI',
  'UYW',
  'XAD',
  'XAG',
  'XAU',
  'XBA',
  'XBB',
  'XBC',
  'XBD',
  'XDR',
  'XPD',
  'XPT',
  'XSU',
  'XTS',
  'XUA',
  'XXX',
]);

const displayName = (currency: Iso4217Currency): string => {
  const name = englishCurrencyNames.of(currency.alphaCode);
  return name === undefined || name === currency.alphaCode ? currency.name : name;
};

export const iso4217Currency = (numericCode: number): Iso4217Currency | null => byNumericCode.get(numericCode) ?? null;

export const formatIso4217Currency = (numericCode: number): string => {
  const currency = iso4217Currency(numericCode);
  return currency ? `${currency.alphaCode} — ${displayName(currency)}` : `ISO ${numericCode}`;
};

export const formatIso4217CurrencyCode = (numericCode: number): string => {
  const currency = iso4217Currency(numericCode);
  return currency ? `${currency.alphaCode} · ${currency.numericCode}` : `ISO ${numericCode}`;
};

const normalizeSearch = (value: string): string =>
  value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLocaleLowerCase('en');

export const searchIso4217Currencies = (
  query: string,
  allowedNumericCodes?: readonly number[],
): readonly Iso4217Currency[] => {
  const allowed = allowedNumericCodes === undefined ? null : new Set(allowedNumericCodes);
  const normalized = normalizeSearch(query.trim());
  return ISO_4217_CURRENCIES.filter((currency) => {
    if (NON_ISSUANCE_ALPHA_CODES.has(currency.alphaCode)) return false;
    if (allowed !== null && !allowed.has(currency.numericCode)) return false;
    if (normalized.length === 0) return true;
    return (
      normalizeSearch(currency.alphaCode).includes(normalized) ||
      normalizeSearch(currency.name).includes(normalized) ||
      normalizeSearch(displayName(currency)).includes(normalized) ||
      String(currency.numericCode).includes(normalized) ||
      currency.territories.some((territory) => normalizeSearch(territory).includes(normalized))
    );
  }).map((currency) => {
    const name = displayName(currency);
    return name === currency.name ? currency : { ...currency, name };
  });
};
